// react/src/TodoList.js
import React from 'react';
import TodoListItem from './TodoListItem';

class TodoList extends React.Component {
  constructor(props) {
    super(props);
    this.onToggleTodoCompleted = this.onToggleTodoCompleted.bind(this);
    this.onRemoveTodo = this.onRemoveTodo.bind(this);
  }

  onToggleTodoCompleted(todo) {
    this.props.toggleCompleted(todo);
  }

  onRemoveTodo(todo) {
    this.props.remove(todo);
  }

  render() {
    if (this.props.todos.length === 0) {
      return null;
    }
    return (
      <section className="main">
        <ul className="todo-list">
          {this.props.todos.map(todo => (
            <li className={todo.completed ? 'completed' : ''} key={todo.id}>
              <TodoListItem
                todo={todo}
                toggleCompleted={this.onToggleTodoCompleted}
                remove={this.onRemoveTodo}
              />
            </li>
          ))}
        </ul>
      </section>
    );
  }
}

export default TodoList;

// angular/src/app/todo-list/todo-list.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Todo } from '../todo';

@Component({
  selector: 'app-todo-list',
  templateUrl: './todo-list.component.html'
})
export class TodoListComponent {
  @Input()
  todos: Todo[];

  @Output()
  remove: EventEmitter<Todo> = new EventEmitter();

  @Output()
  toggleCompleted: EventEmitter<Todo> = new EventEmitter();

  onToggleTodoCompleted(todo: Todo) {
    this.toggleCompleted.emit(todo);
  }

  onRemoveTodo(todo: Todo) {
    this.remove.emit(todo);
  }
}

<section class="main" *ngIf="todos.length > 0">
  <ul class="todo-list">
    <li *ngFor="let todo of todos" [class.completed]="todo.completed">
      <app-todo-list-item [todo]="todo" (toggleCompleted)="onToggleTodoCompleted($event)" (remove)="onRemoveTodo($event)"></app-todo-list-item>
    </li>
  </ul>
</section>
