// angular/src/app/sign-in/sign-in.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { ApiService } from '../api.service';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.css']
})
export class SignInComponent {
  public frm: FormGroup;

  public isBusy = false;
  public hasFailed = false;
  public showInputErrors = false;

  constructor(
    private api: ApiService,
    private auth: AuthService,
    private fb: FormBuilder,
    private router: Router
  ) {
    this.frm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required]
    });
  }

  public doSignIn() {
    if (this.frm.invalid) {
      this.showInputErrors = true;
      return;
    }
    this.isBusy = true;
    this.hasFailed = false;
    const username = this.frm.get('username').value;
    const password = this.frm.get('password').value;
    this.api.signIn(username, password).subscribe(
      response => {
        this.auth.doSignIn(response.token, response.name);
        this.router.navigate(['todos']);
      },
      error => {
        this.isBusy = false;
        this.hasFailed = true;
      }
    );
  }
}

<div class="sign-in-wrapper">
  <form [formGroup]="frm">
    <h1>Todos</h1>
    <input type="text" formControlName="username" placeholder="Your username">
    <div class="input-errors" *ngIf="(frm.get('username').invalid&&frm.get('username').touched) || showInputErrors">
      <div *ngIf="frm.get('username').hasError('required')">
        Please enter your username
      </div>
    </div>
    <input type="password" formControlName="password" placeholder="Your password">
    <div class="input-errors" *ngIf="(frm.get('password').invalid&&frm.get('password').touched) || showInputErrors">
      <div *ngIf="frm.get('password').hasError('required')">
        Please enter your password
      </div>
    </div>
    <div class="sign-in-error" *ngIf="hasFailed">
      Invalid username or password
    </div>
    <button (click)="doSignIn()" [disabled]="isBusy">
      <ng-template [ngIf]="!isBusy">Sign in</ng-template>
      <ng-template [ngIf]="isBusy">Signing in, please wait...</ng-template>
    </button>
    <p class="tip">You can sign in with username "demo" and password "demo".</p>
  </form>
</div>

// react/src/SignIn.js
import React from 'react';
import { Redirect } from 'react-router-dom';
import './SignIn.css';
import { ApiService } from './api-service';
import { AuthService } from './auth-service';

class SignIn extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isBusy: false,
      hasFailed: false,
      showInputErrors: false,
      username: '',
      password: '',
      touchedUsername: false,
      touchedPassword: false,
      navigate: ''
    };
    this.doSignIn = this.doSignIn.bind(this);
    this.handleUsernameChange = this.handleUsernameChange.bind(this);
    this.handlePasswordChange = this.handlePasswordChange.bind(this);
  }

  doSignIn(e) {
    e.preventDefault();
    if (this.state.username === '' || this.state.password === '') {
      this.setState({ showInputErrors: true });
      return;
    }
    this.setState({ isBusy: true, hasFailed: false });
    ApiService.signIn(this.state.username, this.state.password)
      .then(response => {
        AuthService.doSignIn(response.data.token, response.data.name);
        this.setState({ navigate: '/todos' });
      })
      .catch(error => {
        this.setState({ isBusy: false, hasFailed: true });
      });
  }

  handleUsernameChange(e) {
    this.setState({ username: e.target.value });
  }

  handlePasswordChange(e) {
    this.setState({ password: e.target.value });
  }

  render() {
    if (this.state.navigate) {
      return <Redirect to={this.state.navigate} />;
    }
    return (
      <div className="sign-in-wrapper">
        <form onSubmit={this.doSignIn}>
          <h1>Todos</h1>
          <input
            type="text"
            placeholder="Your username"
            value={this.state.username}
            onChange={this.handleUsernameChange}
          />
          {(this.state.username === '' && this.state.touchedUsername) ||
          this.state.showInputErrors ? (
            <div className="input-errors">
              <div>Please enter your username</div>
            </div>
          ) : null}
          <input
            type="password"
            placeholder="Your password"
            value={this.state.password}
            onChange={this.handlePasswordChange}
          />
          {(this.state.password === '' && this.state.touchedPassword) ||
          this.state.showInputErrors ? (
            <div className="input-errors">
              <div>Please enter your password</div>
            </div>
          ) : null}
          {this.state.hasFailed ? (
            <div className="sign-in-error">Invalid username or password</div>
          ) : null}
          <button className="bottom-button" disabled={this.state.isBusy}>
            {this.state.isBusy ? 'Signing in, please wait...' : 'Sign in'}
          </button>
          <p className="tip">You can sign in with username "demo" and password "demo".</p>
        </form>
      </div>
    );
  }
}

export default SignIn;
