// angular/src/app/todo-list-item/todo-list-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Todo } from '../todo';

@Component({
  selector: 'app-todo-list-item',
  templateUrl: './todo-list-item.component.html'
})
export class TodoListItemComponent {
  @Input()
  todo: Todo;

  @Output()
  remove: EventEmitter<Todo> = new EventEmitter();

  @Output()
  toggleCompleted: EventEmitter<Todo> = new EventEmitter();

  toggleTodoCompleted(todo: Todo) {
    this.toggleCompleted.emit(todo);
  }

  removeTodo(todo: Todo) {
    this.remove.emit(todo);
  }
}

<div class="view">
  <input type="checkbox" class="toggle" (click)="toggleTodoCompleted(todo)" [checked]="todo.completed">
  <label>{{todo.title}}</label>
  <button class="destroy" (click)="removeTodo(todo)"></button>
</div>

// react/src/TodoListItem.js
import React from 'react';

function TodoListItem(props) {
  const toggleTodoCompleted = todo => {
    return () => {
      props.toggleCompleted(todo);
    };
  };

  const removeTodo = todo => {
    return () => {
      props.remove(todo);
    };
  };

  return (
    <div className="view">
      <input
        type="checkbox"
        className="toggle"
        checked={props.todo.completed}
        onClick={toggleTodoCompleted(props.todo)}
      />
      <label>{props.todo.title}</label>
      <button className="destroy" onClick={removeTodo(props.todo)}></button>
    </div>
  );
}

export default TodoListItem;
