// react/src/TodoListHeader.js
import React from 'react';

class TodoListHeader extends React.Component {
  constructor(props) {
    super(props);
    this.state = { newTodoTitle: '' };
  }

  handleTodoTitleChange = e => {
    this.setState({ newTodoTitle: e.target.value });
  };

  addTodo = e => {
    if (e.keyCode !== 13 || this.state.newTodoTitle === '') {
      return;
    }
    this.props.add(this.state.newTodoTitle);
    this.setState({ newTodoTitle: '' });
  };

  render() {
    return (
      <header className="header">
        <h1>Todos</h1>
        <input
          type="text"
          className="new-todo"
          placeholder="What needs to be done?"
          autoFocus
          value={this.state.newTodoTitle}
          onChange={this.handleTodoTitleChange}
          onKeyUp={this.addTodo}
        />
      </header>
    );
  }
}

export default TodoListHeader;

// angular/src/app/todo-list-header/todo-list-header.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { Todo } from '../todo';

@Component({
  selector: 'app-todo-list-header',
  templateUrl: './todo-list-header.component.html'
})
export class TodoListHeaderComponent {
  newTodo = new Todo();

  @Output()
  add: EventEmitter<Todo> = new EventEmitter();

  addTodo() {
    if (this.newTodo.title === '') {
      return;
    }
    this.add.emit(this.newTodo);
    this.newTodo = new Todo();
  }
}

<header class="header">
  <h1>Todos</h1>
  <input type="text" class="new-todo" placeholder="What needs to be done?" autofocus [(ngModel)]="newTodo.title" (keyup.enter)="addTodo()">
</header>
