// react/src/Todos.js
import React from 'react';
import { Redirect } from 'react-router-dom';
import './Todos.css';
import TodoListHeader from './TodoListHeader';
import TodoList from './TodoList';
import TodoListFooter from './TodoListFooter';
import { AuthService } from './auth-service';
import { TodoDataService } from './todo-data-service';

class Todos extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      todos: [],
      navigate: ''
    };
    this.doSignOut = this.doSignOut.bind(this);
    this.onAddTodo = this.onAddTodo.bind(this);
    this.onToggleTodoCompleted = this.onToggleTodoCompleted.bind(this);
    this.onRemoveTodo = this.onRemoveTodo.bind(this);

    TodoDataService.getAllTodos().then(response => {
      this.setState({ todos: response.data });
    });
  }

  onAddTodo(newTodoTitle) {
    TodoDataService.addTodo({ title: newTodoTitle, completed: false }).then(response => {
      this.setState({ todos: this.state.todos.concat(response.data) });
    });
  }

  onToggleTodoCompleted(todo) {
    TodoDataService.toggleTodoCompleted(todo).then(response => {
      todo = response.data;
      this.setState({ todos: this.state.todos });
    });
  }

  onRemoveTodo(todo) {
    TodoDataService.deleteTodoByID(todo.id).then(_ => {
      this.setState({ todos: this.state.todos.filter(t => t.id !== todo.id) });
    });
  }

  doSignOut() {
    AuthService.doSignOut();
    this.setState({ navigate: '/sign-in' });
  }

  render() {
    if (!AuthService.isSignedIn()) {
      return <Redirect to="/sign-in" />;
    }
    if (this.state.navigate) {
      return <Redirect to={this.state.navigate} />;
    }
    return (
      <>
        <section className="todoapp">
          <TodoListHeader add={this.onAddTodo} />
          <TodoList
            todos={this.state.todos}
            toggleCompleted={this.onToggleTodoCompleted}
            remove={this.onRemoveTodo}
          />
          <TodoListFooter todos={this.state.todos} />
        </section>
        <button className="bottom-button" onClick={this.doSignOut}>
          Sign out
        </button>
      </>
    );
  }
}

export default Todos;

// angular/src/app/todos/todos.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { TodoDataService } from '../todo-data.service';
import { Todo } from '../todo';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-todos',
  templateUrl: './todos.component.html',
  styleUrls: ['./todos.component.css']
})
export class TodosComponent implements OnInit {
  todos: Todo[] = [];

  constructor(
    private todoDataService: TodoDataService,
    private route: ActivatedRoute,
    private auth: AuthService,
    private router: Router
  ) {}

  ngOnInit() {
    this.route.data.subscribe(data => (this.todos = data.todos));
  }

  onAddTodo(todo) {
    this.todoDataService.addTodo(todo).subscribe(newTodo => {
      this.todos = this.todos.concat(newTodo);
    });
  }

  onToggleTodoCompleted(todo: Todo) {
    this.todoDataService.toggleTodoCompleted(todo).subscribe(updatedTodo => (todo = updatedTodo));
  }

  onRemoveTodo(todo: Todo) {
    this.todoDataService.deleteTodoByID(todo.id).subscribe(_ => {
      this.todos = this.todos.filter(t => t.id !== todo.id);
    });
  }

  doSignOut() {
    this.auth.doSignOut();
    this.router.navigate(['/sign-in']);
  }
}

<section class="todoapp">
  <app-todo-list-header (add)="onAddTodo($event)"></app-todo-list-header>
  <app-todo-list [todos]="todos" (toggleCompleted)="onToggleTodoCompleted($event)" (remove)="onRemoveTodo($event)"></app-todo-list>
  <app-todo-list-footer [todos]="todos"></app-todo-list-footer>
</section>
<button (click)="doSignOut()">Sign out</button>
